from typing import List, Protocol

from schemas.dtos import MahabharataParvaDto, MahabharataVerseDto

class MahabharataService(Protocol):
    async def get_mahabharata_parvas(self) -> List[MahabharataParvaDto]: ...
    async def get_mahabharata_parva(self, parva_number: int) -> MahabharataParvaDto: ...
    async def get_mahabharata_verses(
        self, parva_number: int, chapter_number: int, page: int, size: int
    ) -> List[MahabharataVerseDto]: ...
    async def get_mahabharata_verse(
        self, parva_number: int, chapter_number: int, verse: int
    ) -> MahabharataVerseDto: ...
