"""Service interfaces."""

from __future__ import annotations

from typing import List, Optional, Protocol

from schemas.dtos import (
    AartiDto,
    ChalisaDto,
    ChalisaVerseDto,
    GitaChapterDto,
    GitaVerseDto,
    MahabharataParvaDto,
    MahabharataVerseDto,
    MantraDto,
    RamayanaKandaDto,
    RamayanaVerseDto,
    RigVedaVerseDto,
    SearchResultDto,
    StotramDto,
    UpanishadDto,
    UpanishadVerseDto,
    VedaDto,
)


class GodService(Protocol):
    async def get_aartis(self, deity: Optional[str], page: int, size: int) -> List[AartiDto]: ...
    async def get_aarti_by_id(self, aarti_id: str) -> AartiDto: ...
    async def get_aarti_deities(self) -> List[str]: ...
    async def get_chalisas(self, page: int, size: int) -> List[ChalisaDto]: ...
    async def get_chalisa_by_deity(self, deity: str) -> ChalisaDto: ...
    async def get_chalisa_verse(self, deity: str, verse_number: int) -> ChalisaVerseDto: ...
    async def get_stotrams(self, deity: Optional[str], page: int, size: int) -> List[StotramDto]: ...
    async def get_stotram_by_id(self, stotram_id: str) -> StotramDto: ...
    async def get_random_mantra(self) -> MantraDto: ...
    async def get_mantras(self, deity: Optional[str], limit: int) -> List[MantraDto]: ...


class ScriptureService(Protocol):
    async def get_gita_chapters(self) -> List[GitaChapterDto]: ...
    async def get_gita_chapter(self, chapter_number: int) -> GitaChapterDto: ...
    async def get_gita_verses_by_chapter(self, chapter_number: int) -> List[GitaVerseDto]: ...
    async def get_gita_verse(self, chapter_number: int, verse_number: int) -> GitaVerseDto: ...
    async def get_ramayana_kandas(self) -> List[RamayanaKandaDto]: ...
    async def get_ramayana_kanda(self, kanda_id: str) -> RamayanaKandaDto: ...
    async def get_ramayana_verses(
        self, kanda_id: str, sarga: int, page: int, size: int
    ) -> List[RamayanaVerseDto]: ...
    async def get_ramayana_verse(self, kanda_id: str, sarga: int, verse: int) -> RamayanaVerseDto: ...
    async def get_mahabharata_parvas(self) -> List[MahabharataParvaDto]: ...
    async def get_mahabharata_parva(self, parva_number: int) -> MahabharataParvaDto: ...
    async def get_mahabharata_verses(
        self, parva_number: int, chapter_number: int, page: int, size: int
    ) -> List[MahabharataVerseDto]: ...
    async def get_mahabharata_verse(
        self, parva_number: int, chapter_number: int, verse: int
    ) -> MahabharataVerseDto: ...


class VedaService(Protocol):
    async def get_all_vedas(self) -> List[VedaDto]: ...
    async def get_veda(self, veda_id: str) -> VedaDto: ...
    async def get_rig_veda_by_mandala(self, mandala: int, page: int, size: int) -> List[RigVedaVerseDto]: ...
    async def get_rig_veda_by_deity(self, deity: str, page: int, size: int) -> List[RigVedaVerseDto]: ...
    async def get_rig_veda_by_poet(self, poet: str, page: int, size: int) -> List[RigVedaVerseDto]: ...
    async def get_rig_veda_verse(self, mandala: int, sukta: int, stanza: int) -> RigVedaVerseDto: ...
    async def get_yajur_veda_mantras(self, page: int, size: int) -> List[MantraDto]: ...
    async def get_sama_veda_mantras(self, page: int, size: int) -> List[MantraDto]: ...
    async def get_atharva_veda_mantras(self, page: int, size: int) -> List[MantraDto]: ...
    async def get_upanishads(self) -> List[UpanishadDto]: ...
    async def get_upanishad(self, upanishad_id: str) -> UpanishadDto: ...
    async def get_upanishad_verses(
        self, upanishad_id: str, chapter: int, page: int, size: int
    ) -> List[UpanishadVerseDto]: ...
    async def get_upanishad_verse(
        self, upanishad_id: str, chapter: int, verse: int
    ) -> UpanishadVerseDto: ...
    async def get_random_vedic_mantra(self) -> MantraDto: ...
    async def search_mantras(self, deity: str, limit: int) -> List[MantraDto]: ...


class SearchService(Protocol):
    async def search(
        self, query: str, domain: Optional[str], page: int, size: int
    ) -> List[SearchResultDto]: ...

    async def count(self, query: str, domain: Optional[str]) -> int: ...
