from typing import List, Optional, Protocol

from schemas.dtos import AartiDto

class AartiService(Protocol):
    async def get_aartis(self, deity: Optional[str], page: int, size: int) -> List[AartiDto]: ...
    async def get_aarti_by_id(self, aarti_id: str) -> AartiDto: ...
    async def get_aarti_deities(self) -> List[str]: ...
